name: Run Backend & Frontend Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  backend-tests:
    name: Backend (.NET) Tests
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 8.0.x

      - name: Restore dependencies
        run: dotnet restore backend/MyTODO_API

      - name: Run backend tests
        run: dotnet test backend/MyTODO_API.Tests

  frontend-tests:
    name: Frontend (React) Tests
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install
        working-directory: client

      - name: Run frontend tests
        run: npm test -- --watchAll=false
        working-directory: client
